version: "3.1"
services:
  psychologist-bot:
    image: psychologist-bot
    links:
        - mongo-dbs:mongo-dbs
    volumes:
        - ~/Documents/TFG1920/howru/howru_chatbot:/opt/chatbot
    restart: always
  mongo-dbs:
    image: mongo:4.2.6
    ports:
      - "27017:27017"
    restart: always
  mongo-populator:
    image: mongo-populator
    links:
      - mongo-dbs
  web-interface:
    image: web_interface
    links:
      - mongo-dbs:mongo-dbs
    volumes:
      - ~/Documents/TFG1920/howru/howru_web_interface:/opt/web_interface
    ports:
      - "5025:5025"
    depends_on:
      - nginx
    restart: always

  nginx:
    image: "nginx"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: always


