version: "3.1"
services:
  psychologist-bot:
    image: psychologist-bot
    links:
        - db:db
    volumes:
        - ~/Documents/TFG1920/howru/howru_chatbot:/opt/chatbot
    depends_on:
      - db
    restart: always
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
  web-interface:
    image: web_interface
    links:
        - db:db
    volumes:
      - ~/Documents/TFG1920/howru/howru_web_interface:/opt/web_interface
    ports:
      - "8080:8080"
    depends_on:
      - nginx
      - db
    restart: always

  nginx:
    image: "nginx"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: always


